Agregar funcion Login POST en userControlle y Cors a Program.cs
IvanJGG/Login_Backend pull request #3
Opened 2024-09-10 18:33 UTC by IvanJGG

2024-09-10 19:44 UTC, gcachuo requested changes

2024-09-10 19:44 UTC, gcachuo commented on Login/Controllers/UserController.cs
>          return Ok(new { mensaje = "Hola yo soy un GET" });
Elimina metodo inecesario

2024-09-10 19:44 UTC, gcachuo commented on Login/Controllers/UserController.cs
>          return Ok(new { mensaje = "Hola yo soy un POST", cuerpo = $"Gracias tu usuario es: {userLogin.Username} Tu contraseña es: {userLogin.Password}"});
Elimina metodo inecesario

2024-09-12 00:15 UTC, IvanJGG commented on Login/Controllers/UserController.cs
>          return Ok(new { mensaje = "Hola yo soy un POST", cuerpo = $"Gracias tu usuario es: {userLogin.Username} Tu contraseña es: {userLogin.Password}"});
ese puedo modificarlo para hacer registrar?

2024-09-12 16:01 UTC, gcachuo approved these changes

2024-09-12 16:02 UTC, merged